#!/bin/sh

# Linux
alias update='yay -Syyu --noconfirm'
alias search='yay -Ss'
alias install='yay -Sy'
alias remove='yay -R'
alias uninstall='yay -R'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# Easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# List
alias ls='colorls --color=always --hyperlink'
alias ll='colorls -la --color=always --hyperlink'

# Git
alias TOMI_GIT='git@github.com:TomiVidal99'
alias gcom='git commit -m '
alias gpush='git push'
alias gpull='git pull'
alias gaddall='git add .'
alias gstatus='git status'
alias gcheckout='git checkout '
alias gbranch='git branch'
alias gdiff='git diff'
alias acp='git_add_commit_push'

# Custom functions
alias awd='add_to_working_directory'
alias rwd='remove_from_working_directory'

# Octave
alias o='octave --traditional'

# Node (PNPM)
alias pp='pnpm'

# Ollama/open-webui run container command
#alias jarvis='sudo docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main'
alias jarvis='sudo docker run -d --network=host -v open-webui:/app/backend/data -e OLLAMA_BASE_URL=http://127.0.0.1:11434 --name open-webui --restart always ghcr.io/open-webui/open-webui:main'

# Docker
alias dshow='sudo docker stats'
