#!/bin/sh

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# git
alias gcom='git commit -m '
alias gpush='git push'
alias gpull='git pull'
alias gaddall='git add .'
alias gstatus='git status'
alias gcheckout='git checkout '
alias gbranch='git branch'
alias gdiff='git diff'
