#!/bin/sh
# Some utility functions for zsh shit

# Source files if they exist
function zsh_add_file() {
    [ -f "$ZDOTDIR/$1" ] && source "$ZDOTDIR/$1"
}

# add plugin, download it if needed
function zsh_add_plugin() {
    PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
    if [ -d "$ZDOTDIR/plugins_dependencies/$PLUGIN_NAME" ]; then 
        # For plugins
        zsh_add_file "plugins_dependencies/$PLUGIN_NAME/$PLUGIN_NAME.plugin.zsh" || \
        zsh_add_file "plugins_dependencies/$PLUGIN_NAME/$PLUGIN_NAME.zsh"
    else
        git clone "https://github.com/$1.git" "$ZDOTDIR/plugins_dependencies/$PLUGIN_NAME"
    fi
}

# check if the current directory is a GIT directory
function is_git_directory() {
  if git tag > /dev/null 2>&1; then
  else
      clear
      RED='\033[0;31m'
      RESET='\033[0m'
      echo -e "${RED}NO REPOSITORY!${RESET}"
  fi
}

# prompt the user for a commit message
function get_commit_message() {
  read "msg?Commit message: "
  git commit -m "${msg}"
}

# switch between the defined working directories.
function switch_working_directory() {
  DIRECTORIES=~/.dotfiles/.config/zsh/directories
  WORKING_DIRECTORIES=~/.dotfiles/.config/zsh/working_directories
  WDIRS=$(cat $DIRECTORIES $WORKING_DIRECTORIES)
  DIR=$(echo $WDIRS | cut -d'=' -f1 | fzf)
  FULLPATH=$(echo $WDIRS | grep $DIR | cut -d'=' -f2)
  if [ -d $FULLPATH ]; then
    cd $FULLPATH
  else
    echo "'${FULLPATH}' doesn't exist."
  fi
}

# add the current directory to the working directories list
function add_to_working_directory() {
  echo "you've entered ${DIR_NAME}"
  #if ! [ -z "$dir_name" ]; then
  #  echo "The name is empty"
  #fi
  #current_dir=$(pwd)
  #echo $current_dir
}

# git add all, commit with a given argument and push changes
function git_add_commit_push() {
  if [ "${1}" ]; then
    git add .
    git commit -m $1
    git push
  else
    echo "ERROR: no commit message."
    echo "Usage: acp 'this is a commit message.'"
  fi
}
