#!/bin/sh
# Options for zsh
# TYPE: man zshoptions
# and set all the options properly.

# Some global variables needed by vim pluging primarly
export EDITOR="nvim"
export TERMINAL="konsole"
export BROWSER="firefox"

# fzf default options
export FZF_DEFAULT_OPTS='--layout=reverse --cycle --border'

# Some commmon options
setopt autocd extendedglob nomatch menucomplete
setopt interactive_comments
stty stop undef		# Disable ctrl-s to freeze terminal.
zle_highlight=('paste:none')
unsetopt BEEP

# Vi mode, from plugin: https://github.com/softmoth/zsh-vim-mode
# Bind for escape
VIM_MODE_VICMD_KEY='^[a'
# Remove delay when changing between modes
KEYTIMEOUT=1
# Enable <Esc>-prefixed bindings that should rarely conflict with NORMAL mode
VIM_MODE_ESC_PREFIXED_WANTED='^?^Hbdfhul.g'  
# Change the cursor on different modes
MODE_CURSOR_VIINS="#00ff00 blinking bar"
MODE_CURSOR_REPLACE="$MODE_CURSOR_VIINS #ff0000"
MODE_CURSOR_VICMD="green block"
MODE_CURSOR_SEARCH="#ff00ff steady underline"
MODE_CURSOR_VISUAL="$MODE_CURSOR_VICMD steady bar"
MODE_CURSOR_VLINE="$MODE_CURSOR_VISUAL #00ffff"
# Start in normal mode
VIM_MODE_INITIAL_KEYMAP=vicmd
