#!/bin/sh
# Plugins for zsh

# Plugins
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
zsh_add_plugin "hlissner/zsh-autopair"
zsh_add_plugin "softmoth/zsh-vim-mode"
zsh_add_plugin "joshskidmore/zsh-fzf-history-search" # more info in: https://github.com/joshskidmore/zsh-fzf-history-search

POWERLEVEL10K_INSTALL_DIR=~/.powerlevel10k

if [ ! -d "$POWERLEVEL10K_INSTALL_DIR" ]; then
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $POWERLEVEL10K_INSTALL_DIR
fi

source "$POWERLEVEL10K_INSTALL_DIR/powerlevel10k.zsh-theme"
